### ISSUE TITLE
formatting issues with new thread post

### ISSUE THREAD

**Issue by roxannedebeaux** [cyclestreets/cyclescape#833]
All line breaks were lost and font is strange. 

https://camcycle.cyclescape.org/threads/4517

<img width="654" alt="screenshot 2019-01-16 at 18 29 14" src="https://user-images.githubusercontent.com/11997264/51270473-e94a0880-19bc-11e9-974a-0883a052ab33.png">

**Comment by nikolai-b** [comment]
@roxannedebeaux did you see the rich text editor when you were writing the message?
I.e. the buttons above the message text box like this:
![screenshot from 2019-01-16 20-39-14](https://user-images.githubusercontent.com/6289830/51277212-d7716100-19ce-11e9-9180-ef8270fe7fc7.png)

**Comment by nikolai-b** [comment]
Also how did you get text in the text box, did you paste from elsewhere?  I'm struggling to reproduce this and sadly I can't fix it till I can.

**Comment by mvl22** [comment]
Nikolai, can we set up logging of POSTs from the form, to see what the client is actually sending whenever the messages are posted. We need to try to narrow down what is causing it.

Can we also log clearly whether postings are coming from web or e-mail.

**Comment by mvl22** [comment]
I think there is a common factor that this is happening with the creation of the thread - see `/threads/4517`, and `/threads/4517`. There may be other situations, but this is an observed situation.

**Comment by roxannedebeaux** [comment]
I can't remember if it was a format box. I did type directly and paste in
some text, but it looked normal (with line breaks) when I pressed send.

Kind Regards,

Roxanne De Beaux
Executive Director

Usual working days MON - THURS

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join:*camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *Text "CYCC11 £5"
to 70070
*Charity no. 1138098*

**Comment by nikolai-b** [comment]
```ruby
Message.joins(:thread).where.not(message_threads: {privacy: :private})
  .where(in_reply_to_id: nil).where("messages.created_at > ?", Rails.cache.fetch("html_format_time"))
  .where.not("body ILIKE '<p%'").pluck(:body, :id)
  .each do |(body, id)|
    Message.where(id: id).update_all(body: ActionController::Base.helpers.simple_format(body))
  end
```
@mvl22 I've updated the existing messages to fix formatting (posting the above code in-case there is a mistake so I've got a record of it).

**Comment by mvl22** [comment]
> I've updated the existing messages to fix formatting

Thanks. This problem does finally seem to have gone away now - so much better!

**Comment by mvl22** [comment]
Actually, this doesn't seem to have been fixed up in private messages, e.g. thread 4542. Could you do that? It's possible that is the original problem not having been fixed there.

**Comment by mvl22** [comment]
> Actually, this doesn't seem to have been fixed up in private messages

Could you run a fixup process to deal with existing threads? E.g. 4542 still looks messy.

**Comment by nikolai-b** [comment]
@mvl22 because of #660 the fix is only on staging.  I can fix up once that is live.

**Comment by mvl22** [comment]
Ah, OK thanks.

**Comment by roxannedebeaux** [comment]
This is still happening with new administrative threads. e.g.
https://camcycle.cyclescape.org/threads/4671

Line breaks did not come through.

Kind Regards,

Roxanne De Beaux
Executive Director

Usual working days MON - THURS

*CAMCYCLE**p: *07482 735174    *e: *roxanne.debeaux@camcycle.org.uk    *w: *
camcycle.org.uk <http://www.camcycle.org.uk/>*    t: *@camcycle
<http://www.twitter.com/camcycle>
*Join: *camcycle.org.uk/membership
<http://www.camcycle.org.uk/membership/join>*     Donate: *
camcycle.org.uk/donate <https://www.camcycle.org.uk/membership/donate/>
*Charity no. 1138098*

**Comment by nikolai-b** [comment]
I've updated existing messages with:
```ruby
Message.joins(:thread).where(message_threads: {privacy: :private}).
  where("messages.created_at > ?", Rails.cache.fetch("html_format_time")).where.not("body ILIKE '%<p%'").
  pluck(:body, :id).each do |(body, id)|
    Message.where(id: id).update_all(body: ActionController::Base.helpers.auto_link(ActionController::Base.helpers.simple_format(body)))
  end
```

**Comment by mvl22** [comment]
That opening of the first message is still showing wrongly - see thread 4671.

**Comment by nikolai-b** [comment]
Ah, sorry I missed updating committee threads.  I've now also run:

```ruby
Message.joins(:thread).where(message_threads: {privacy: :committee}).
  where("messages.created_at > ?", Rails.cache.fetch("html_format_time")).where.not("body ILIKE '%<p%'").
  pluck(:body, :id).each do |(body, id)|
    Message.where(id: id).update_all(body: ActionController::Base.helpers.auto_link(ActionController::Base.helpers.simple_format(body)))
  end
```

If there are any more problems would you mind opening an new issue as that make it easier for me to keep track as this issue is covering many different bugs.
